// Code generated by github.com/upamune/purevipsgen from libvips 8.17.0; DO NOT EDIT.

#include <stdlib.h>
#include <vips/vips.h>
#include <vips/vector.h>

// Prerequisites to build, get outputs and cleanup a vips operation

int purevipsgen_operation_execute(VipsOperation *operation, ...);
int purevipsgen_operation_save_buffer(VipsOperation *operation, void** buf, size_t* len);
int purevipsgen_set_source(VipsOperation *operation, const char *name, VipsSource *value);
int purevipsgen_set_target(VipsOperation *operation, const char *name, VipsTarget *value);
int purevipsgen_set_int(VipsOperation *operation, const char *name, int value);
int purevipsgen_set_keep(VipsOperation *operation, int value);
int purevipsgen_set_bool(VipsOperation *operation, const char *name, gboolean value);
int purevipsgen_set_double(VipsOperation *operation, const char *name, double value);
int purevipsgen_set_guint64(VipsOperation *operation, const char *name, guint64 value);
int purevipsgen_set_string(VipsOperation *operation, const char *name, const char *value);
int purevipsgen_set_image(VipsOperation *operation, const char *name, VipsImage *value);
int purevipsgen_set_array_double(VipsOperation *operation, const char *name, VipsArrayDouble *value);
int purevipsgen_set_array_int(VipsOperation *operation, const char *name, VipsArrayInt *value);
int purevipsgen_set_array_image(VipsOperation *operation, const char *name, VipsArrayImage *value);
int purevipsgen_set_interpolate(VipsOperation *operation, const char *name, VipsInterpolate *value);

// Generated operations

int purevipsgen_CMC2LCh(VipsImage* in, VipsImage** out);

int purevipsgen_CMYK2XYZ(VipsImage* in, VipsImage** out);

int purevipsgen_HSV2sRGB(VipsImage* in, VipsImage** out);

int purevipsgen_LCh2CMC(VipsImage* in, VipsImage** out);

int purevipsgen_LCh2Lab(VipsImage* in, VipsImage** out);

int purevipsgen_Lab2LCh(VipsImage* in, VipsImage** out);

int purevipsgen_Lab2LabQ(VipsImage* in, VipsImage** out);

int purevipsgen_Lab2LabS(VipsImage* in, VipsImage** out);

int purevipsgen_Lab2XYZ(VipsImage* in, VipsImage** out);
int purevipsgen_Lab2XYZ_with_options(VipsImage* in, VipsImage** out, double* temp, int temp_n);

int purevipsgen_LabQ2Lab(VipsImage* in, VipsImage** out);

int purevipsgen_LabQ2LabS(VipsImage* in, VipsImage** out);

int purevipsgen_LabQ2sRGB(VipsImage* in, VipsImage** out);

int purevipsgen_LabS2Lab(VipsImage* in, VipsImage** out);

int purevipsgen_LabS2LabQ(VipsImage* in, VipsImage** out);

int purevipsgen_XYZ2CMYK(VipsImage* in, VipsImage** out);

int purevipsgen_XYZ2Lab(VipsImage* in, VipsImage** out);
int purevipsgen_XYZ2Lab_with_options(VipsImage* in, VipsImage** out, double* temp, int temp_n);

int purevipsgen_XYZ2Yxy(VipsImage* in, VipsImage** out);

int purevipsgen_XYZ2scRGB(VipsImage* in, VipsImage** out);

int purevipsgen_Yxy2XYZ(VipsImage* in, VipsImage** out);

int purevipsgen_abs(VipsImage* in, VipsImage** out);

int purevipsgen_add(VipsImage* left, VipsImage* right, VipsImage** out);

int purevipsgen_addalpha(VipsImage* in, VipsImage** out);

int purevipsgen_affine(VipsImage* in, VipsImage** out, double a, double b, double c, double d);
int purevipsgen_affine_with_options(VipsImage* in, VipsImage** out, double a, double b, double c, double d, VipsInterpolate* interpolate, int* oarea, int oarea_n, double odx, double ody, double idx, double idy, double* background, int background_n, gboolean premultiplied, VipsExtend extend);

int purevipsgen_analyzeload(const char* filename, VipsImage** out);
int purevipsgen_analyzeload_with_options(const char* filename, VipsImage** out, gboolean memory, VipsAccess access, VipsFailOn fail_on, gboolean revalidate);

int purevipsgen_arrayjoin(VipsImage** in, VipsImage** out, int n);
int purevipsgen_arrayjoin_with_options(VipsImage** in, VipsImage** out, int n, gint across, gint shim, double* background, int background_n, VipsAlign halign, VipsAlign valign, gint hspacing, gint vspacing);

int purevipsgen_autorot(VipsImage* in, VipsImage** out);
int purevipsgen_autorot_with_options(VipsImage* in, VipsImage** out, gboolean* flip);

int purevipsgen_avg(VipsImage* in, double* out);

int purevipsgen_bandbool(VipsImage* in, VipsImage** out, VipsOperationBoolean boolean);

int purevipsgen_bandfold(VipsImage* in, VipsImage** out);
int purevipsgen_bandfold_with_options(VipsImage* in, VipsImage** out, gint factor);

int purevipsgen_bandjoin(VipsImage** in, VipsImage** out, int n);

int purevipsgen_bandjoin_const(VipsImage* in, VipsImage** out, double* c, int n);

int purevipsgen_bandmean(VipsImage* in, VipsImage** out);

int purevipsgen_bandrank(VipsImage** in, VipsImage** out, int n);
int purevipsgen_bandrank_with_options(VipsImage** in, VipsImage** out, int n, gint index);

int purevipsgen_bandunfold(VipsImage* in, VipsImage** out);
int purevipsgen_bandunfold_with_options(VipsImage* in, VipsImage** out, gint factor);

int purevipsgen_black(VipsImage** out, gint width, gint height);
int purevipsgen_black_with_options(VipsImage** out, gint width, gint height, gint bands);

int purevipsgen_boolean(VipsImage* left, VipsImage* right, VipsImage** out, VipsOperationBoolean boolean);

int purevipsgen_boolean_const(VipsImage* in, VipsImage** out, VipsOperationBoolean boolean, double* c, int n);

int purevipsgen_buildlut(VipsImage* in, VipsImage** out);

int purevipsgen_byteswap(VipsImage* in, VipsImage** out);

int purevipsgen_canny(VipsImage* in, VipsImage** out);
int purevipsgen_canny_with_options(VipsImage* in, VipsImage** out, double sigma, VipsPrecision precision);

int purevipsgen_case(VipsImage* index, VipsImage** cases, VipsImage** out, int n);

int purevipsgen_cast(VipsImage* in, VipsImage** out, VipsBandFormat format);
int purevipsgen_cast_with_options(VipsImage* in, VipsImage** out, VipsBandFormat format, gboolean shift);

int purevipsgen_clamp(VipsImage* in, VipsImage** out);
int purevipsgen_clamp_with_options(VipsImage* in, VipsImage** out, double min, double max);

int purevipsgen_colourspace(VipsImage* in, VipsImage** out, VipsInterpretation space);
int purevipsgen_colourspace_with_options(VipsImage* in, VipsImage** out, VipsInterpretation space, VipsInterpretation source_space);

int purevipsgen_compass(VipsImage* in, VipsImage** out, VipsImage* mask);
int purevipsgen_compass_with_options(VipsImage* in, VipsImage** out, VipsImage* mask, gint times, VipsAngle45 angle, VipsCombine combine, VipsPrecision precision, gint layers, gint cluster);

int purevipsgen_complex(VipsImage* in, VipsImage** out, VipsOperationComplex cmplx);

int purevipsgen_complex2(VipsImage* left, VipsImage* right, VipsImage** out, VipsOperationComplex2 cmplx);

int purevipsgen_complexform(VipsImage* left, VipsImage* right, VipsImage** out);

int purevipsgen_complexget(VipsImage* in, VipsImage** out, VipsOperationComplexget get);

int purevipsgen_composite(VipsImage** in, VipsImage** out, int n, int* mode);
int purevipsgen_composite_with_options(VipsImage** in, VipsImage** out, int n, int* mode, int* x, int x_n, int* y, int y_n, VipsInterpretation compositing_space, gboolean premultiplied);

int purevipsgen_composite2(VipsImage* base, VipsImage* overlay, VipsImage** out, VipsBlendMode mode);
int purevipsgen_composite2_with_options(VipsImage* base, VipsImage* overlay, VipsImage** out, VipsBlendMode mode, gint x, gint y, VipsInterpretation compositing_space, gboolean premultiplied);

int purevipsgen_conv(VipsImage* in, VipsImage** out, VipsImage* mask);
int purevipsgen_conv_with_options(VipsImage* in, VipsImage** out, VipsImage* mask, VipsPrecision precision, gint layers, gint cluster);

int purevipsgen_conva(VipsImage* in, VipsImage** out, VipsImage* mask);
int purevipsgen_conva_with_options(VipsImage* in, VipsImage** out, VipsImage* mask, gint layers, gint cluster);

int purevipsgen_convasep(VipsImage* in, VipsImage** out, VipsImage* mask);
int purevipsgen_convasep_with_options(VipsImage* in, VipsImage** out, VipsImage* mask, gint layers);

int purevipsgen_convf(VipsImage* in, VipsImage** out, VipsImage* mask);

int purevipsgen_convi(VipsImage* in, VipsImage** out, VipsImage* mask);

int purevipsgen_convsep(VipsImage* in, VipsImage** out, VipsImage* mask);
int purevipsgen_convsep_with_options(VipsImage* in, VipsImage** out, VipsImage* mask, VipsPrecision precision, gint layers, gint cluster);

int purevipsgen_copy(VipsImage* in, VipsImage** out);
int purevipsgen_copy_with_options(VipsImage* in, VipsImage** out, gint width, gint height, gint bands, VipsBandFormat format, VipsCoding coding, VipsInterpretation interpretation, double xres, double yres, gint xoffset, gint yoffset);

int purevipsgen_countlines(VipsImage* in, double* nolines, VipsDirection direction);

int purevipsgen_csvload(const char* filename, VipsImage** out);
int purevipsgen_csvload_with_options(const char* filename, VipsImage** out, gint skip, gint lines, const char* whitespace, const char* separator, gboolean memory, VipsAccess access, VipsFailOn fail_on, gboolean revalidate);

int purevipsgen_csvload_source(VipsSourceCustom* source, VipsImage** out);
int purevipsgen_csvload_source_with_options(VipsSourceCustom* source, VipsImage** out, gint skip, gint lines, const char* whitespace, const char* separator, gboolean memory, VipsAccess access, VipsFailOn fail_on, gboolean revalidate);

int purevipsgen_csvsave(VipsImage* in, const char* filename);
int purevipsgen_csvsave_with_options(VipsImage* in, const char* filename, const char* separator, VipsForeignKeep keep, double* background, int background_n, gint page_height, const char* profile);

int purevipsgen_csvsave_target(VipsImage* in, VipsTargetCustom* target);
int purevipsgen_csvsave_target_with_options(VipsImage* in, VipsTargetCustom* target, const char* separator, VipsForeignKeep keep, double* background, int background_n, gint page_height, const char* profile);

int purevipsgen_dE00(VipsImage* left, VipsImage* right, VipsImage** out);

int purevipsgen_dE76(VipsImage* left, VipsImage* right, VipsImage** out);

int purevipsgen_dECMC(VipsImage* left, VipsImage* right, VipsImage** out);

int purevipsgen_deviate(VipsImage* in, double* out);

int purevipsgen_divide(VipsImage* left, VipsImage* right, VipsImage** out);

int purevipsgen_draw_circle(VipsImage* image, double* ink, int n, gint cx, gint cy, gint radius);
int purevipsgen_draw_circle_with_options(VipsImage* image, double* ink, int n, gint cx, gint cy, gint radius, gboolean fill);

int purevipsgen_draw_flood(VipsImage* image, double* ink, int n, gint x, gint y);
int purevipsgen_draw_flood_with_options(VipsImage* image, double* ink, int n, gint x, gint y, VipsImage* test, gboolean equal, gint* left, gint* top, gint* width, gint* height);

int purevipsgen_draw_image(VipsImage* image, VipsImage* sub, gint x, gint y);
int purevipsgen_draw_image_with_options(VipsImage* image, VipsImage* sub, gint x, gint y, VipsCombineMode mode);

int purevipsgen_draw_line(VipsImage* image, double* ink, int n, gint x1, gint y1, gint x2, gint y2);

int purevipsgen_draw_mask(VipsImage* image, double* ink, int n, VipsImage* mask, gint x, gint y);

int purevipsgen_draw_rect(VipsImage* image, double* ink, int n, gint left, gint top, gint width, gint height);
int purevipsgen_draw_rect_with_options(VipsImage* image, double* ink, int n, gint left, gint top, gint width, gint height, gboolean fill);

int purevipsgen_draw_smudge(VipsImage* image, gint left, gint top, gint width, gint height);

int purevipsgen_dzsave(VipsImage* in, const char* filename);
int purevipsgen_dzsave_with_options(VipsImage* in, const char* filename, const char* imagename, VipsForeignDzLayout layout, const char* suffix, gint overlap, gint tile_size, gboolean centre, VipsForeignDzDepth depth, VipsAngle angle, VipsForeignDzContainer container, gint compression, VipsRegionShrink region_shrink, gint skip_blanks, const char* id, gint Q, VipsForeignKeep keep, double* background, int background_n, gint page_height, const char* profile);

int purevipsgen_dzsave_buffer(VipsImage* in, void** buf, size_t* len);
int purevipsgen_dzsave_buffer_with_options(VipsImage* in, void** buf, size_t* len, const char* imagename, VipsForeignDzLayout layout, const char* suffix, gint overlap, gint tile_size, gboolean centre, VipsForeignDzDepth depth, VipsAngle angle, VipsForeignDzContainer container, gint compression, VipsRegionShrink region_shrink, gint skip_blanks, const char* id, gint Q, VipsForeignKeep keep, double* background, int background_n, gint page_height, const char* profile);

int purevipsgen_dzsave_target(VipsImage* in, VipsTargetCustom* target);
int purevipsgen_dzsave_target_with_options(VipsImage* in, VipsTargetCustom* target, const char* imagename, VipsForeignDzLayout layout, const char* suffix, gint overlap, gint tile_size, gboolean centre, VipsForeignDzDepth depth, VipsAngle angle, VipsForeignDzContainer container, gint compression, VipsRegionShrink region_shrink, gint skip_blanks, const char* id, gint Q, VipsForeignKeep keep, double* background, int background_n, gint page_height, const char* profile);

int purevipsgen_embed(VipsImage* in, VipsImage** out, gint x, gint y, gint width, gint height);
int purevipsgen_embed_with_options(VipsImage* in, VipsImage** out, gint x, gint y, gint width, gint height, VipsExtend extend, double* background, int background_n);

int purevipsgen_extract_area(VipsImage* input, VipsImage** out, gint left, gint top, gint width, gint height);

int purevipsgen_extract_band(VipsImage* in, VipsImage** out, gint band);
int purevipsgen_extract_band_with_options(VipsImage* in, VipsImage** out, gint band, gint n);

int purevipsgen_eye(VipsImage** out, gint width, gint height);
int purevipsgen_eye_with_options(VipsImage** out, gint width, gint height, gboolean uchar, double factor);

int purevipsgen_falsecolour(VipsImage* in, VipsImage** out);

int purevipsgen_fastcor(VipsImage* in, VipsImage* ref, VipsImage** out);

int purevipsgen_fill_nearest(VipsImage* in, VipsImage** out);

int purevipsgen_find_trim(VipsImage* in, gint* left, gint* top, gint* width, gint* height);
int purevipsgen_find_trim_with_options(VipsImage* in, gint* left, gint* top, gint* width, gint* height, double threshold, double* background, int background_n, gboolean line_art);

int purevipsgen_fitsload(const char* filename, VipsImage** out);
int purevipsgen_fitsload_with_options(const char* filename, VipsImage** out, gboolean memory, VipsAccess access, VipsFailOn fail_on, gboolean revalidate);

int purevipsgen_fitssave(VipsImage* in, const char* filename);
int purevipsgen_fitssave_with_options(VipsImage* in, const char* filename, VipsForeignKeep keep, double* background, int background_n, gint page_height, const char* profile);

int purevipsgen_flatten(VipsImage* in, VipsImage** out);
int purevipsgen_flatten_with_options(VipsImage* in, VipsImage** out, double* background, int background_n, double max_alpha);

int purevipsgen_flip(VipsImage* in, VipsImage** out, VipsDirection direction);

int purevipsgen_float2rad(VipsImage* in, VipsImage** out);

int purevipsgen_fractsurf(VipsImage** out, gint width, gint height, double fractal_dimension);

int purevipsgen_freqmult(VipsImage* in, VipsImage* mask, VipsImage** out);

int purevipsgen_fwfft(VipsImage* in, VipsImage** out);

int purevipsgen_gamma(VipsImage* in, VipsImage** out);
int purevipsgen_gamma_with_options(VipsImage* in, VipsImage** out, double exponent);

int purevipsgen_gaussblur(VipsImage* in, VipsImage** out, double sigma);
int purevipsgen_gaussblur_with_options(VipsImage* in, VipsImage** out, double sigma, double min_ampl, VipsPrecision precision);

int purevipsgen_gaussmat(VipsImage** out, double sigma, double min_ampl);
int purevipsgen_gaussmat_with_options(VipsImage** out, double sigma, double min_ampl, gboolean separable, VipsPrecision precision);

int purevipsgen_gaussnoise(VipsImage** out, gint width, gint height);
int purevipsgen_gaussnoise_with_options(VipsImage** out, gint width, gint height, double sigma, double mean, gint seed);

int purevipsgen_getpoint(VipsImage* in, double** out_array, int* n, gint x, gint y);
int purevipsgen_getpoint_with_options(VipsImage* in, double** out_array, int* n, gint x, gint y, gboolean unpack_complex);

int purevipsgen_gifload(const char* filename, VipsImage** out);
int purevipsgen_gifload_with_options(const char* filename, VipsImage** out, gint n, gint page, gboolean memory, VipsAccess access, VipsFailOn fail_on, gboolean revalidate);

int purevipsgen_gifload_buffer(void* buf, size_t len, VipsImage** out);
int purevipsgen_gifload_buffer_with_options(void* buf, size_t len, VipsImage** out, gint n, gint page, gboolean memory, VipsAccess access, VipsFailOn fail_on, gboolean revalidate);

int purevipsgen_gifload_source(VipsSourceCustom* source, VipsImage** out);
int purevipsgen_gifload_source_with_options(VipsSourceCustom* source, VipsImage** out, gint n, gint page, gboolean memory, VipsAccess access, VipsFailOn fail_on, gboolean revalidate);

int purevipsgen_gifsave(VipsImage* in, const char* filename);
int purevipsgen_gifsave_with_options(VipsImage* in, const char* filename, double dither, gint effort, gint bitdepth, double interframe_maxerror, gboolean reuse, double interpalette_maxerror, gboolean interlace, gboolean keep_duplicate_frames, VipsForeignKeep keep, double* background, int background_n, gint page_height, const char* profile);

int purevipsgen_gifsave_buffer(VipsImage* in, void** buf, size_t* len);
int purevipsgen_gifsave_buffer_with_options(VipsImage* in, void** buf, size_t* len, double dither, gint effort, gint bitdepth, double interframe_maxerror, gboolean reuse, double interpalette_maxerror, gboolean interlace, gboolean keep_duplicate_frames, VipsForeignKeep keep, double* background, int background_n, gint page_height, const char* profile);

int purevipsgen_gifsave_target(VipsImage* in, VipsTargetCustom* target);
int purevipsgen_gifsave_target_with_options(VipsImage* in, VipsTargetCustom* target, double dither, gint effort, gint bitdepth, double interframe_maxerror, gboolean reuse, double interpalette_maxerror, gboolean interlace, gboolean keep_duplicate_frames, VipsForeignKeep keep, double* background, int background_n, gint page_height, const char* profile);

int purevipsgen_globalbalance(VipsImage* in, VipsImage** out);
int purevipsgen_globalbalance_with_options(VipsImage* in, VipsImage** out, double gamma, gboolean int_output);

int purevipsgen_gravity(VipsImage* in, VipsImage** out, VipsCompassDirection direction, gint width, gint height);
int purevipsgen_gravity_with_options(VipsImage* in, VipsImage** out, VipsCompassDirection direction, gint width, gint height, VipsExtend extend, double* background, int background_n);

int purevipsgen_grey(VipsImage** out, gint width, gint height);
int purevipsgen_grey_with_options(VipsImage** out, gint width, gint height, gboolean uchar);

int purevipsgen_grid(VipsImage* in, VipsImage** out, gint tile_height, gint across, gint down);

int purevipsgen_heifload(const char* filename, VipsImage** out);
int purevipsgen_heifload_with_options(const char* filename, VipsImage** out, gint page, gint n, gboolean thumbnail, gboolean unlimited, gboolean memory, VipsAccess access, VipsFailOn fail_on, gboolean revalidate);

int purevipsgen_heifload_buffer(void* buf, size_t len, VipsImage** out);
int purevipsgen_heifload_buffer_with_options(void* buf, size_t len, VipsImage** out, gint page, gint n, gboolean thumbnail, gboolean unlimited, gboolean memory, VipsAccess access, VipsFailOn fail_on, gboolean revalidate);

int purevipsgen_heifload_source(VipsSourceCustom* source, VipsImage** out);
int purevipsgen_heifload_source_with_options(VipsSourceCustom* source, VipsImage** out, gint page, gint n, gboolean thumbnail, gboolean unlimited, gboolean memory, VipsAccess access, VipsFailOn fail_on, gboolean revalidate);

int purevipsgen_heifsave(VipsImage* in, const char* filename);
int purevipsgen_heifsave_with_options(VipsImage* in, const char* filename, gint Q, gint bitdepth, gboolean lossless, VipsForeignHeifCompression compression, gint effort, VipsForeignSubsample subsample_mode, VipsForeignHeifEncoder encoder, VipsForeignKeep keep, double* background, int background_n, gint page_height, const char* profile);

int purevipsgen_heifsave_buffer(VipsImage* in, void** buf, size_t* len);
int purevipsgen_heifsave_buffer_with_options(VipsImage* in, void** buf, size_t* len, gint Q, gint bitdepth, gboolean lossless, VipsForeignHeifCompression compression, gint effort, VipsForeignSubsample subsample_mode, VipsForeignHeifEncoder encoder, VipsForeignKeep keep, double* background, int background_n, gint page_height, const char* profile);

int purevipsgen_heifsave_target(VipsImage* in, VipsTargetCustom* target);
int purevipsgen_heifsave_target_with_options(VipsImage* in, VipsTargetCustom* target, gint Q, gint bitdepth, gboolean lossless, VipsForeignHeifCompression compression, gint effort, VipsForeignSubsample subsample_mode, VipsForeignHeifEncoder encoder, VipsForeignKeep keep, double* background, int background_n, gint page_height, const char* profile);

int purevipsgen_hist_cum(VipsImage* in, VipsImage** out);

int purevipsgen_hist_entropy(VipsImage* in, double* out);

int purevipsgen_hist_equal(VipsImage* in, VipsImage** out);
int purevipsgen_hist_equal_with_options(VipsImage* in, VipsImage** out, gint band);

int purevipsgen_hist_find(VipsImage* in, VipsImage** out);
int purevipsgen_hist_find_with_options(VipsImage* in, VipsImage** out, gint band);

int purevipsgen_hist_find_indexed(VipsImage* in, VipsImage* index, VipsImage** out);
int purevipsgen_hist_find_indexed_with_options(VipsImage* in, VipsImage* index, VipsImage** out, VipsCombine combine);

int purevipsgen_hist_find_ndim(VipsImage* in, VipsImage** out);
int purevipsgen_hist_find_ndim_with_options(VipsImage* in, VipsImage** out, gint bins);

int purevipsgen_hist_ismonotonic(VipsImage* in, gboolean* monotonic);

int purevipsgen_hist_local(VipsImage* in, VipsImage** out, gint width, gint height);
int purevipsgen_hist_local_with_options(VipsImage* in, VipsImage** out, gint width, gint height, gint max_slope);

int purevipsgen_hist_match(VipsImage* in, VipsImage* ref, VipsImage** out);

int purevipsgen_hist_norm(VipsImage* in, VipsImage** out);

int purevipsgen_hist_plot(VipsImage* in, VipsImage** out);

int purevipsgen_hough_circle(VipsImage* in, VipsImage** out);
int purevipsgen_hough_circle_with_options(VipsImage* in, VipsImage** out, gint scale, gint min_radius, gint max_radius);

int purevipsgen_hough_line(VipsImage* in, VipsImage** out);
int purevipsgen_hough_line_with_options(VipsImage* in, VipsImage** out, gint width, gint height);

int purevipsgen_icc_export(VipsImage* in, VipsImage** out);
int purevipsgen_icc_export_with_options(VipsImage* in, VipsImage** out, VipsPCS pcs, VipsIntent intent, gboolean black_point_compensation, const char* output_profile, gint depth);

int purevipsgen_icc_import(VipsImage* in, VipsImage** out);
int purevipsgen_icc_import_with_options(VipsImage* in, VipsImage** out, VipsPCS pcs, VipsIntent intent, gboolean black_point_compensation, gboolean embedded, const char* input_profile);

int purevipsgen_icc_transform(VipsImage* in, VipsImage** out, const char* output_profile);
int purevipsgen_icc_transform_with_options(VipsImage* in, VipsImage** out, const char* output_profile, VipsPCS pcs, VipsIntent intent, gboolean black_point_compensation, gboolean embedded, const char* input_profile, gint depth);

int purevipsgen_identity(VipsImage** out);
int purevipsgen_identity_with_options(VipsImage** out, gint bands, gboolean ushort, gint size);

int purevipsgen_ifthenelse(VipsImage* cond, VipsImage* in1, VipsImage* in2, VipsImage** out);
int purevipsgen_ifthenelse_with_options(VipsImage* cond, VipsImage* in1, VipsImage* in2, VipsImage** out, gboolean blend);

int purevipsgen_insert(VipsImage* main, VipsImage* sub, VipsImage** out, gint x, gint y);
int purevipsgen_insert_with_options(VipsImage* main, VipsImage* sub, VipsImage** out, gint x, gint y, gboolean expand, double* background, int background_n);

int purevipsgen_invert(VipsImage* in, VipsImage** out);

int purevipsgen_invertlut(VipsImage* in, VipsImage** out);
int purevipsgen_invertlut_with_options(VipsImage* in, VipsImage** out, gint size);

int purevipsgen_invfft(VipsImage* in, VipsImage** out);
int purevipsgen_invfft_with_options(VipsImage* in, VipsImage** out, gboolean real);

int purevipsgen_join(VipsImage* in1, VipsImage* in2, VipsImage** out, VipsDirection direction);
int purevipsgen_join_with_options(VipsImage* in1, VipsImage* in2, VipsImage** out, VipsDirection direction, gboolean expand, gint shim, double* background, int background_n, VipsAlign align);

int purevipsgen_jp2kload(const char* filename, VipsImage** out);
int purevipsgen_jp2kload_with_options(const char* filename, VipsImage** out, gint page, gboolean oneshot, gboolean memory, VipsAccess access, VipsFailOn fail_on, gboolean revalidate);

int purevipsgen_jp2kload_buffer(void* buf, size_t len, VipsImage** out);
int purevipsgen_jp2kload_buffer_with_options(void* buf, size_t len, VipsImage** out, gint page, gboolean oneshot, gboolean memory, VipsAccess access, VipsFailOn fail_on, gboolean revalidate);

int purevipsgen_jp2kload_source(VipsSourceCustom* source, VipsImage** out);
int purevipsgen_jp2kload_source_with_options(VipsSourceCustom* source, VipsImage** out, gint page, gboolean oneshot, gboolean memory, VipsAccess access, VipsFailOn fail_on, gboolean revalidate);

int purevipsgen_jp2ksave(VipsImage* in, const char* filename);
int purevipsgen_jp2ksave_with_options(VipsImage* in, const char* filename, gint tile_width, gint tile_height, gboolean lossless, gint Q, VipsForeignSubsample subsample_mode, VipsForeignKeep keep, double* background, int background_n, gint page_height, const char* profile);

int purevipsgen_jp2ksave_buffer(VipsImage* in, void** buf, size_t* len);
int purevipsgen_jp2ksave_buffer_with_options(VipsImage* in, void** buf, size_t* len, gint tile_width, gint tile_height, gboolean lossless, gint Q, VipsForeignSubsample subsample_mode, VipsForeignKeep keep, double* background, int background_n, gint page_height, const char* profile);

int purevipsgen_jp2ksave_target(VipsImage* in, VipsTargetCustom* target);
int purevipsgen_jp2ksave_target_with_options(VipsImage* in, VipsTargetCustom* target, gint tile_width, gint tile_height, gboolean lossless, gint Q, VipsForeignSubsample subsample_mode, VipsForeignKeep keep, double* background, int background_n, gint page_height, const char* profile);

int purevipsgen_jpegload(const char* filename, VipsImage** out);
int purevipsgen_jpegload_with_options(const char* filename, VipsImage** out, gint shrink, gboolean autorotate, gboolean unlimited, gboolean memory, VipsAccess access, VipsFailOn fail_on, gboolean revalidate);

int purevipsgen_jpegload_buffer(void* buf, size_t len, VipsImage** out);
int purevipsgen_jpegload_buffer_with_options(void* buf, size_t len, VipsImage** out, gint shrink, gboolean autorotate, gboolean unlimited, gboolean memory, VipsAccess access, VipsFailOn fail_on, gboolean revalidate);

int purevipsgen_jpegload_source(VipsSourceCustom* source, VipsImage** out);
int purevipsgen_jpegload_source_with_options(VipsSourceCustom* source, VipsImage** out, gint shrink, gboolean autorotate, gboolean unlimited, gboolean memory, VipsAccess access, VipsFailOn fail_on, gboolean revalidate);

int purevipsgen_jpegsave(VipsImage* in, const char* filename);
int purevipsgen_jpegsave_with_options(VipsImage* in, const char* filename, gint Q, gboolean optimize_coding, gboolean interlace, gboolean trellis_quant, gboolean overshoot_deringing, gboolean optimize_scans, gint quant_table, VipsForeignSubsample subsample_mode, gint restart_interval, VipsForeignKeep keep, double* background, int background_n, gint page_height, const char* profile);

int purevipsgen_jpegsave_buffer(VipsImage* in, void** buf, size_t* len);
int purevipsgen_jpegsave_buffer_with_options(VipsImage* in, void** buf, size_t* len, gint Q, gboolean optimize_coding, gboolean interlace, gboolean trellis_quant, gboolean overshoot_deringing, gboolean optimize_scans, gint quant_table, VipsForeignSubsample subsample_mode, gint restart_interval, VipsForeignKeep keep, double* background, int background_n, gint page_height, const char* profile);

int purevipsgen_jpegsave_target(VipsImage* in, VipsTargetCustom* target);
int purevipsgen_jpegsave_target_with_options(VipsImage* in, VipsTargetCustom* target, gint Q, gboolean optimize_coding, gboolean interlace, gboolean trellis_quant, gboolean overshoot_deringing, gboolean optimize_scans, gint quant_table, VipsForeignSubsample subsample_mode, gint restart_interval, VipsForeignKeep keep, double* background, int background_n, gint page_height, const char* profile);

int purevipsgen_jxlload(const char* filename, VipsImage** out);
int purevipsgen_jxlload_with_options(const char* filename, VipsImage** out, gint page, gint n, gboolean memory, VipsAccess access, VipsFailOn fail_on, gboolean revalidate);

int purevipsgen_jxlload_buffer(void* buf, size_t len, VipsImage** out);
int purevipsgen_jxlload_buffer_with_options(void* buf, size_t len, VipsImage** out, gint page, gint n, gboolean memory, VipsAccess access, VipsFailOn fail_on, gboolean revalidate);

int purevipsgen_jxlload_source(VipsSourceCustom* source, VipsImage** out);
int purevipsgen_jxlload_source_with_options(VipsSourceCustom* source, VipsImage** out, gint page, gint n, gboolean memory, VipsAccess access, VipsFailOn fail_on, gboolean revalidate);

int purevipsgen_jxlsave(VipsImage* in, const char* filename);
int purevipsgen_jxlsave_with_options(VipsImage* in, const char* filename, gint tier, double distance, gint effort, gboolean lossless, gint Q, VipsForeignKeep keep, double* background, int background_n, gint page_height, const char* profile);

int purevipsgen_jxlsave_buffer(VipsImage* in, void** buf, size_t* len);
int purevipsgen_jxlsave_buffer_with_options(VipsImage* in, void** buf, size_t* len, gint tier, double distance, gint effort, gboolean lossless, gint Q, VipsForeignKeep keep, double* background, int background_n, gint page_height, const char* profile);

int purevipsgen_jxlsave_target(VipsImage* in, VipsTargetCustom* target);
int purevipsgen_jxlsave_target_with_options(VipsImage* in, VipsTargetCustom* target, gint tier, double distance, gint effort, gboolean lossless, gint Q, VipsForeignKeep keep, double* background, int background_n, gint page_height, const char* profile);

int purevipsgen_labelregions(VipsImage* in, VipsImage** mask);
int purevipsgen_labelregions_with_options(VipsImage* in, VipsImage** mask, gint* segments);

int purevipsgen_linear(VipsImage* in, VipsImage** out, double* a, double* b, int n);
int purevipsgen_linear_with_options(VipsImage* in, VipsImage** out, double* a, double* b, int n, gboolean uchar);

int purevipsgen_linecache(VipsImage* in, VipsImage** out);
int purevipsgen_linecache_with_options(VipsImage* in, VipsImage** out, gint tile_height, VipsAccess access, gboolean threaded, gboolean persistent);

int purevipsgen_logmat(VipsImage** out, double sigma, double min_ampl);
int purevipsgen_logmat_with_options(VipsImage** out, double sigma, double min_ampl, gboolean separable, VipsPrecision precision);

int purevipsgen_magickload(const char* filename, VipsImage** out);
int purevipsgen_magickload_with_options(const char* filename, VipsImage** out, const char* density, gint page, gint n, gboolean memory, VipsAccess access, VipsFailOn fail_on, gboolean revalidate);

int purevipsgen_magickload_buffer(void* buf, size_t len, VipsImage** out);
int purevipsgen_magickload_buffer_with_options(void* buf, size_t len, VipsImage** out, const char* density, gint page, gint n, gboolean memory, VipsAccess access, VipsFailOn fail_on, gboolean revalidate);

int purevipsgen_magicksave(VipsImage* in, const char* filename);
int purevipsgen_magicksave_with_options(VipsImage* in, const char* filename, const char* format, gint quality, gboolean optimize_gif_frames, gboolean optimize_gif_transparency, gint bitdepth, VipsForeignKeep keep, double* background, int background_n, gint page_height, const char* profile);

int purevipsgen_magicksave_buffer(VipsImage* in, void** buf, size_t* len);
int purevipsgen_magicksave_buffer_with_options(VipsImage* in, void** buf, size_t* len, const char* format, gint quality, gboolean optimize_gif_frames, gboolean optimize_gif_transparency, gint bitdepth, VipsForeignKeep keep, double* background, int background_n, gint page_height, const char* profile);

int purevipsgen_mapim(VipsImage* in, VipsImage** out, VipsImage* index);
int purevipsgen_mapim_with_options(VipsImage* in, VipsImage** out, VipsImage* index, VipsInterpolate* interpolate, double* background, int background_n, gboolean premultiplied, VipsExtend extend);

int purevipsgen_maplut(VipsImage* in, VipsImage** out, VipsImage* lut);
int purevipsgen_maplut_with_options(VipsImage* in, VipsImage** out, VipsImage* lut, gint band);

int purevipsgen_mask_butterworth(VipsImage** out, gint width, gint height, double order, double frequency_cutoff, double amplitude_cutoff);
int purevipsgen_mask_butterworth_with_options(VipsImage** out, gint width, gint height, double order, double frequency_cutoff, double amplitude_cutoff, gboolean uchar, gboolean nodc, gboolean reject, gboolean optical);

int purevipsgen_mask_butterworth_band(VipsImage** out, gint width, gint height, double order, double frequency_cutoff_x, double frequency_cutoff_y, double radius, double amplitude_cutoff);
int purevipsgen_mask_butterworth_band_with_options(VipsImage** out, gint width, gint height, double order, double frequency_cutoff_x, double frequency_cutoff_y, double radius, double amplitude_cutoff, gboolean uchar, gboolean nodc, gboolean reject, gboolean optical);

int purevipsgen_mask_butterworth_ring(VipsImage** out, gint width, gint height, double order, double frequency_cutoff, double amplitude_cutoff, double ringwidth);
int purevipsgen_mask_butterworth_ring_with_options(VipsImage** out, gint width, gint height, double order, double frequency_cutoff, double amplitude_cutoff, double ringwidth, gboolean uchar, gboolean nodc, gboolean reject, gboolean optical);

int purevipsgen_mask_fractal(VipsImage** out, gint width, gint height, double fractal_dimension);
int purevipsgen_mask_fractal_with_options(VipsImage** out, gint width, gint height, double fractal_dimension, gboolean uchar, gboolean nodc, gboolean reject, gboolean optical);

int purevipsgen_mask_gaussian(VipsImage** out, gint width, gint height, double frequency_cutoff, double amplitude_cutoff);
int purevipsgen_mask_gaussian_with_options(VipsImage** out, gint width, gint height, double frequency_cutoff, double amplitude_cutoff, gboolean uchar, gboolean nodc, gboolean reject, gboolean optical);

int purevipsgen_mask_gaussian_band(VipsImage** out, gint width, gint height, double frequency_cutoff_x, double frequency_cutoff_y, double radius, double amplitude_cutoff);
int purevipsgen_mask_gaussian_band_with_options(VipsImage** out, gint width, gint height, double frequency_cutoff_x, double frequency_cutoff_y, double radius, double amplitude_cutoff, gboolean uchar, gboolean nodc, gboolean reject, gboolean optical);

int purevipsgen_mask_gaussian_ring(VipsImage** out, gint width, gint height, double frequency_cutoff, double amplitude_cutoff, double ringwidth);
int purevipsgen_mask_gaussian_ring_with_options(VipsImage** out, gint width, gint height, double frequency_cutoff, double amplitude_cutoff, double ringwidth, gboolean uchar, gboolean nodc, gboolean reject, gboolean optical);

int purevipsgen_mask_ideal(VipsImage** out, gint width, gint height, double frequency_cutoff);
int purevipsgen_mask_ideal_with_options(VipsImage** out, gint width, gint height, double frequency_cutoff, gboolean uchar, gboolean nodc, gboolean reject, gboolean optical);

int purevipsgen_mask_ideal_band(VipsImage** out, gint width, gint height, double frequency_cutoff_x, double frequency_cutoff_y, double radius);
int purevipsgen_mask_ideal_band_with_options(VipsImage** out, gint width, gint height, double frequency_cutoff_x, double frequency_cutoff_y, double radius, gboolean uchar, gboolean nodc, gboolean reject, gboolean optical);

int purevipsgen_mask_ideal_ring(VipsImage** out, gint width, gint height, double frequency_cutoff, double ringwidth);
int purevipsgen_mask_ideal_ring_with_options(VipsImage** out, gint width, gint height, double frequency_cutoff, double ringwidth, gboolean uchar, gboolean nodc, gboolean reject, gboolean optical);

int purevipsgen_match(VipsImage* ref, VipsImage* sec, VipsImage** out, gint xr1, gint yr1, gint xs1, gint ys1, gint xr2, gint yr2, gint xs2, gint ys2);
int purevipsgen_match_with_options(VipsImage* ref, VipsImage* sec, VipsImage** out, gint xr1, gint yr1, gint xs1, gint ys1, gint xr2, gint yr2, gint xs2, gint ys2, gint hwindow, gint harea, gboolean search, VipsInterpolate* interpolate);

int purevipsgen_math(VipsImage* in, VipsImage** out, VipsOperationMath math);

int purevipsgen_math2(VipsImage* left, VipsImage* right, VipsImage** out, VipsOperationMath2 math2);

int purevipsgen_math2_const(VipsImage* in, VipsImage** out, VipsOperationMath2 math2, double* c, int n);

int purevipsgen_matload(const char* filename, VipsImage** out);
int purevipsgen_matload_with_options(const char* filename, VipsImage** out, gboolean memory, VipsAccess access, VipsFailOn fail_on, gboolean revalidate);

int purevipsgen_matrixinvert(VipsImage* in, VipsImage** out);

int purevipsgen_matrixload(const char* filename, VipsImage** out);
int purevipsgen_matrixload_with_options(const char* filename, VipsImage** out, gboolean memory, VipsAccess access, VipsFailOn fail_on, gboolean revalidate);

int purevipsgen_matrixload_source(VipsSourceCustom* source, VipsImage** out);
int purevipsgen_matrixload_source_with_options(VipsSourceCustom* source, VipsImage** out, gboolean memory, VipsAccess access, VipsFailOn fail_on, gboolean revalidate);

int purevipsgen_matrixmultiply(VipsImage* left, VipsImage* right, VipsImage** out);

int purevipsgen_matrixprint(VipsImage* in);
int purevipsgen_matrixprint_with_options(VipsImage* in, VipsForeignKeep keep, double* background, int background_n, gint page_height, const char* profile);

int purevipsgen_matrixsave(VipsImage* in, const char* filename);
int purevipsgen_matrixsave_with_options(VipsImage* in, const char* filename, VipsForeignKeep keep, double* background, int background_n, gint page_height, const char* profile);

int purevipsgen_matrixsave_target(VipsImage* in, VipsTargetCustom* target);
int purevipsgen_matrixsave_target_with_options(VipsImage* in, VipsTargetCustom* target, VipsForeignKeep keep, double* background, int background_n, gint page_height, const char* profile);

int purevipsgen_max(VipsImage* in, double* out);
int purevipsgen_max_with_options(VipsImage* in, double* out, gint size, gint* x, gint* y);

int purevipsgen_maxpair(VipsImage* left, VipsImage* right, VipsImage** out);

int purevipsgen_measure(VipsImage* in, VipsImage** out, gint h, gint v);
int purevipsgen_measure_with_options(VipsImage* in, VipsImage** out, gint h, gint v, gint left, gint top, gint width, gint height);

int purevipsgen_merge(VipsImage* ref, VipsImage* sec, VipsImage** out, VipsDirection direction, gint dx, gint dy);
int purevipsgen_merge_with_options(VipsImage* ref, VipsImage* sec, VipsImage** out, VipsDirection direction, gint dx, gint dy, gint mblend);

int purevipsgen_min(VipsImage* in, double* out);
int purevipsgen_min_with_options(VipsImage* in, double* out, gint size, gint* x, gint* y);

int purevipsgen_minpair(VipsImage* left, VipsImage* right, VipsImage** out);

int purevipsgen_morph(VipsImage* in, VipsImage** out, VipsImage* mask, VipsOperationMorphology morph);

int purevipsgen_mosaic(VipsImage* ref, VipsImage* sec, VipsImage** out, VipsDirection direction, gint xref, gint yref, gint xsec, gint ysec);
int purevipsgen_mosaic_with_options(VipsImage* ref, VipsImage* sec, VipsImage** out, VipsDirection direction, gint xref, gint yref, gint xsec, gint ysec, gint hwindow, gint harea, gint mblend, gint bandno, gint* dx0, gint* dy0, double* scale1, double* angle1, double* dy1, double* dx1);

int purevipsgen_mosaic1(VipsImage* ref, VipsImage* sec, VipsImage** out, VipsDirection direction, gint xr1, gint yr1, gint xs1, gint ys1, gint xr2, gint yr2, gint xs2, gint ys2);
int purevipsgen_mosaic1_with_options(VipsImage* ref, VipsImage* sec, VipsImage** out, VipsDirection direction, gint xr1, gint yr1, gint xs1, gint ys1, gint xr2, gint yr2, gint xs2, gint ys2, gint hwindow, gint harea, gboolean search, VipsInterpolate* interpolate, gint mblend);

int purevipsgen_msb(VipsImage* in, VipsImage** out);
int purevipsgen_msb_with_options(VipsImage* in, VipsImage** out, gint band);

int purevipsgen_multiply(VipsImage* left, VipsImage* right, VipsImage** out);

int purevipsgen_openexrload(const char* filename, VipsImage** out);
int purevipsgen_openexrload_with_options(const char* filename, VipsImage** out, gboolean memory, VipsAccess access, VipsFailOn fail_on, gboolean revalidate);

int purevipsgen_openslideload(const char* filename, VipsImage** out);
int purevipsgen_openslideload_with_options(const char* filename, VipsImage** out, gint level, gboolean autocrop, const char* associated, gboolean attach_associated, gboolean rgb, gboolean memory, VipsAccess access, VipsFailOn fail_on, gboolean revalidate);

int purevipsgen_openslideload_source(VipsSourceCustom* source, VipsImage** out);
int purevipsgen_openslideload_source_with_options(VipsSourceCustom* source, VipsImage** out, gint level, gboolean autocrop, const char* associated, gboolean attach_associated, gboolean rgb, gboolean memory, VipsAccess access, VipsFailOn fail_on, gboolean revalidate);

int purevipsgen_pdfload(const char* filename, VipsImage** out);
int purevipsgen_pdfload_with_options(const char* filename, VipsImage** out, gint page, gint n, double dpi, double scale, double* background, int background_n, const char* password, gboolean memory, VipsAccess access, VipsFailOn fail_on, gboolean revalidate);

int purevipsgen_pdfload_buffer(void* buf, size_t len, VipsImage** out);
int purevipsgen_pdfload_buffer_with_options(void* buf, size_t len, VipsImage** out, gint page, gint n, double dpi, double scale, double* background, int background_n, const char* password, gboolean memory, VipsAccess access, VipsFailOn fail_on, gboolean revalidate);

int purevipsgen_pdfload_source(VipsSourceCustom* source, VipsImage** out);
int purevipsgen_pdfload_source_with_options(VipsSourceCustom* source, VipsImage** out, gint page, gint n, double dpi, double scale, double* background, int background_n, const char* password, gboolean memory, VipsAccess access, VipsFailOn fail_on, gboolean revalidate);

int purevipsgen_percent(VipsImage* in, double percent, gint* threshold);

int purevipsgen_perlin(VipsImage** out, gint width, gint height);
int purevipsgen_perlin_with_options(VipsImage** out, gint width, gint height, gint cell_size, gboolean uchar, gint seed);

int purevipsgen_phasecor(VipsImage* in, VipsImage* in2, VipsImage** out);

int purevipsgen_pngload(const char* filename, VipsImage** out);
int purevipsgen_pngload_with_options(const char* filename, VipsImage** out, gboolean unlimited, gboolean memory, VipsAccess access, VipsFailOn fail_on, gboolean revalidate);

int purevipsgen_pngload_buffer(void* buf, size_t len, VipsImage** out);
int purevipsgen_pngload_buffer_with_options(void* buf, size_t len, VipsImage** out, gboolean unlimited, gboolean memory, VipsAccess access, VipsFailOn fail_on, gboolean revalidate);

int purevipsgen_pngload_source(VipsSourceCustom* source, VipsImage** out);
int purevipsgen_pngload_source_with_options(VipsSourceCustom* source, VipsImage** out, gboolean unlimited, gboolean memory, VipsAccess access, VipsFailOn fail_on, gboolean revalidate);

int purevipsgen_pngsave(VipsImage* in, const char* filename);
int purevipsgen_pngsave_with_options(VipsImage* in, const char* filename, gint compression, gboolean interlace, VipsForeignPngFilter filter, gboolean palette, gint Q, double dither, gint bitdepth, gint effort, VipsForeignKeep keep, double* background, int background_n, gint page_height, const char* profile);

int purevipsgen_pngsave_buffer(VipsImage* in, void** buf, size_t* len);
int purevipsgen_pngsave_buffer_with_options(VipsImage* in, void** buf, size_t* len, gint compression, gboolean interlace, VipsForeignPngFilter filter, gboolean palette, gint Q, double dither, gint bitdepth, gint effort, VipsForeignKeep keep, double* background, int background_n, gint page_height, const char* profile);

int purevipsgen_pngsave_target(VipsImage* in, VipsTargetCustom* target);
int purevipsgen_pngsave_target_with_options(VipsImage* in, VipsTargetCustom* target, gint compression, gboolean interlace, VipsForeignPngFilter filter, gboolean palette, gint Q, double dither, gint bitdepth, gint effort, VipsForeignKeep keep, double* background, int background_n, gint page_height, const char* profile);

int purevipsgen_ppmload(const char* filename, VipsImage** out);
int purevipsgen_ppmload_with_options(const char* filename, VipsImage** out, gboolean memory, VipsAccess access, VipsFailOn fail_on, gboolean revalidate);

int purevipsgen_ppmload_buffer(void* buf, size_t len, VipsImage** out);
int purevipsgen_ppmload_buffer_with_options(void* buf, size_t len, VipsImage** out, gboolean memory, VipsAccess access, VipsFailOn fail_on, gboolean revalidate);

int purevipsgen_ppmload_source(VipsSourceCustom* source, VipsImage** out);
int purevipsgen_ppmload_source_with_options(VipsSourceCustom* source, VipsImage** out, gboolean memory, VipsAccess access, VipsFailOn fail_on, gboolean revalidate);

int purevipsgen_ppmsave(VipsImage* in, const char* filename);
int purevipsgen_ppmsave_with_options(VipsImage* in, const char* filename, VipsForeignPpmFormat format, gboolean ascii, gint bitdepth, VipsForeignKeep keep, double* background, int background_n, gint page_height, const char* profile);

int purevipsgen_ppmsave_target(VipsImage* in, VipsTargetCustom* target);
int purevipsgen_ppmsave_target_with_options(VipsImage* in, VipsTargetCustom* target, VipsForeignPpmFormat format, gboolean ascii, gint bitdepth, VipsForeignKeep keep, double* background, int background_n, gint page_height, const char* profile);

int purevipsgen_premultiply(VipsImage* in, VipsImage** out);
int purevipsgen_premultiply_with_options(VipsImage* in, VipsImage** out, double max_alpha);

int purevipsgen_prewitt(VipsImage* in, VipsImage** out);

int purevipsgen_profile(VipsImage* in, VipsImage** columns, VipsImage** rows);

int purevipsgen_profile_load(const char* name, VipsBlob** profile);

int purevipsgen_project(VipsImage* in, VipsImage** columns, VipsImage** rows);

int purevipsgen_quadratic(VipsImage* in, VipsImage** out, VipsImage* coeff);
int purevipsgen_quadratic_with_options(VipsImage* in, VipsImage** out, VipsImage* coeff, VipsInterpolate* interpolate);

int purevipsgen_rad2float(VipsImage* in, VipsImage** out);

int purevipsgen_radload(const char* filename, VipsImage** out);
int purevipsgen_radload_with_options(const char* filename, VipsImage** out, gboolean memory, VipsAccess access, VipsFailOn fail_on, gboolean revalidate);

int purevipsgen_radload_buffer(void* buf, size_t len, VipsImage** out);
int purevipsgen_radload_buffer_with_options(void* buf, size_t len, VipsImage** out, gboolean memory, VipsAccess access, VipsFailOn fail_on, gboolean revalidate);

int purevipsgen_radload_source(VipsSourceCustom* source, VipsImage** out);
int purevipsgen_radload_source_with_options(VipsSourceCustom* source, VipsImage** out, gboolean memory, VipsAccess access, VipsFailOn fail_on, gboolean revalidate);

int purevipsgen_radsave(VipsImage* in, const char* filename);
int purevipsgen_radsave_with_options(VipsImage* in, const char* filename, VipsForeignKeep keep, double* background, int background_n, gint page_height, const char* profile);

int purevipsgen_radsave_buffer(VipsImage* in, void** buf, size_t* len);
int purevipsgen_radsave_buffer_with_options(VipsImage* in, void** buf, size_t* len, VipsForeignKeep keep, double* background, int background_n, gint page_height, const char* profile);

int purevipsgen_radsave_target(VipsImage* in, VipsTargetCustom* target);
int purevipsgen_radsave_target_with_options(VipsImage* in, VipsTargetCustom* target, VipsForeignKeep keep, double* background, int background_n, gint page_height, const char* profile);

int purevipsgen_rank(VipsImage* in, VipsImage** out, gint width, gint height, gint index);

int purevipsgen_rawload(const char* filename, VipsImage** out, gint width, gint height, gint bands);
int purevipsgen_rawload_with_options(const char* filename, VipsImage** out, gint width, gint height, gint bands, guint64 offset, VipsBandFormat format, VipsInterpretation interpretation, gboolean memory, VipsAccess access, VipsFailOn fail_on, gboolean revalidate);

int purevipsgen_rawsave(VipsImage* in, const char* filename);
int purevipsgen_rawsave_with_options(VipsImage* in, const char* filename, VipsForeignKeep keep, double* background, int background_n, gint page_height, const char* profile);

int purevipsgen_rawsave_buffer(VipsImage* in, void** buf, size_t* len);
int purevipsgen_rawsave_buffer_with_options(VipsImage* in, void** buf, size_t* len, VipsForeignKeep keep, double* background, int background_n, gint page_height, const char* profile);

int purevipsgen_rawsave_target(VipsImage* in, VipsTargetCustom* target);
int purevipsgen_rawsave_target_with_options(VipsImage* in, VipsTargetCustom* target, VipsForeignKeep keep, double* background, int background_n, gint page_height, const char* profile);

int purevipsgen_recomb(VipsImage* in, VipsImage** out, VipsImage* m);

int purevipsgen_reduce(VipsImage* in, VipsImage** out, double hshrink, double vshrink);
int purevipsgen_reduce_with_options(VipsImage* in, VipsImage** out, double hshrink, double vshrink, VipsKernel kernel, double gap);

int purevipsgen_reduceh(VipsImage* in, VipsImage** out, double hshrink);
int purevipsgen_reduceh_with_options(VipsImage* in, VipsImage** out, double hshrink, VipsKernel kernel, double gap);

int purevipsgen_reducev(VipsImage* in, VipsImage** out, double vshrink);
int purevipsgen_reducev_with_options(VipsImage* in, VipsImage** out, double vshrink, VipsKernel kernel, double gap);

int purevipsgen_relational(VipsImage* left, VipsImage* right, VipsImage** out, VipsOperationRelational relational);

int purevipsgen_relational_const(VipsImage* in, VipsImage** out, VipsOperationRelational relational, double* c, int n);

int purevipsgen_remainder(VipsImage* left, VipsImage* right, VipsImage** out);

int purevipsgen_remainder_const(VipsImage* in, VipsImage** out, double* c, int n);

int purevipsgen_remosaic(VipsImage* in, VipsImage** out, const char* old_str, const char* new_str);

int purevipsgen_replicate(VipsImage* in, VipsImage** out, gint across, gint down);

int purevipsgen_resize(VipsImage* in, VipsImage** out, double scale);
int purevipsgen_resize_with_options(VipsImage* in, VipsImage** out, double scale, VipsKernel kernel, double gap, double vscale);

int purevipsgen_rot(VipsImage* in, VipsImage** out, VipsAngle angle);

int purevipsgen_rot45(VipsImage* in, VipsImage** out);
int purevipsgen_rot45_with_options(VipsImage* in, VipsImage** out, VipsAngle45 angle);

int purevipsgen_rotate(VipsImage* in, VipsImage** out, double angle);
int purevipsgen_rotate_with_options(VipsImage* in, VipsImage** out, double angle, VipsInterpolate* interpolate, double* background, int background_n, double odx, double ody, double idx, double idy);

int purevipsgen_round(VipsImage* in, VipsImage** out, VipsOperationRound round);

int purevipsgen_sRGB2HSV(VipsImage* in, VipsImage** out);

int purevipsgen_sRGB2scRGB(VipsImage* in, VipsImage** out);

int purevipsgen_scRGB2BW(VipsImage* in, VipsImage** out);
int purevipsgen_scRGB2BW_with_options(VipsImage* in, VipsImage** out, gint depth);

int purevipsgen_scRGB2XYZ(VipsImage* in, VipsImage** out);

int purevipsgen_scRGB2sRGB(VipsImage* in, VipsImage** out);
int purevipsgen_scRGB2sRGB_with_options(VipsImage* in, VipsImage** out, gint depth);

int purevipsgen_scale(VipsImage* in, VipsImage** out);
int purevipsgen_scale_with_options(VipsImage* in, VipsImage** out, double exp, gboolean log);

int purevipsgen_scharr(VipsImage* in, VipsImage** out);

int purevipsgen_sdf(VipsImage** out, gint width, gint height, VipsSdfShape shape);
int purevipsgen_sdf_with_options(VipsImage** out, gint width, gint height, VipsSdfShape shape, double r, double* a, int a_n, double* b, int b_n, double* corners, int corners_n);

int purevipsgen_sequential(VipsImage* in, VipsImage** out);
int purevipsgen_sequential_with_options(VipsImage* in, VipsImage** out, gint tile_height);

int purevipsgen_sharpen(VipsImage* in, VipsImage** out);
int purevipsgen_sharpen_with_options(VipsImage* in, VipsImage** out, double sigma, double x1, double y2, double y3, double m1, double m2);

int purevipsgen_shrink(VipsImage* in, VipsImage** out, double hshrink, double vshrink);
int purevipsgen_shrink_with_options(VipsImage* in, VipsImage** out, double hshrink, double vshrink, gboolean ceil);

int purevipsgen_shrinkh(VipsImage* in, VipsImage** out, gint hshrink);
int purevipsgen_shrinkh_with_options(VipsImage* in, VipsImage** out, gint hshrink, gboolean ceil);

int purevipsgen_shrinkv(VipsImage* in, VipsImage** out, gint vshrink);
int purevipsgen_shrinkv_with_options(VipsImage* in, VipsImage** out, gint vshrink, gboolean ceil);

int purevipsgen_sign(VipsImage* in, VipsImage** out);

int purevipsgen_similarity(VipsImage* in, VipsImage** out);
int purevipsgen_similarity_with_options(VipsImage* in, VipsImage** out, double scale, double angle, VipsInterpolate* interpolate, double* background, int background_n, double odx, double ody, double idx, double idy);

int purevipsgen_sines(VipsImage** out, gint width, gint height);
int purevipsgen_sines_with_options(VipsImage** out, gint width, gint height, gboolean uchar, double hfreq, double vfreq);

int purevipsgen_smartcrop(VipsImage* input, VipsImage** out, gint width, gint height);
int purevipsgen_smartcrop_with_options(VipsImage* input, VipsImage** out, gint width, gint height, VipsInteresting interesting, gboolean premultiplied, gint* attention_x, gint* attention_y);

int purevipsgen_sobel(VipsImage* in, VipsImage** out);

int purevipsgen_spcor(VipsImage* in, VipsImage* ref, VipsImage** out);

int purevipsgen_spectrum(VipsImage* in, VipsImage** out);

int purevipsgen_stats(VipsImage* in, VipsImage** out);

int purevipsgen_stdif(VipsImage* in, VipsImage** out, gint width, gint height);
int purevipsgen_stdif_with_options(VipsImage* in, VipsImage** out, gint width, gint height, double s0, double b, double m0, double a);

int purevipsgen_subsample(VipsImage* input, VipsImage** out, gint xfac, gint yfac);
int purevipsgen_subsample_with_options(VipsImage* input, VipsImage** out, gint xfac, gint yfac, gboolean point);

int purevipsgen_subtract(VipsImage* left, VipsImage* right, VipsImage** out);

int purevipsgen_sum(VipsImage** in, VipsImage** out, int n);

int purevipsgen_svgload(const char* filename, VipsImage** out);
int purevipsgen_svgload_with_options(const char* filename, VipsImage** out, double dpi, double scale, gboolean unlimited, const char* stylesheet, gboolean high_bitdepth, gboolean memory, VipsAccess access, VipsFailOn fail_on, gboolean revalidate);

int purevipsgen_svgload_buffer(void* buf, size_t len, VipsImage** out);
int purevipsgen_svgload_buffer_with_options(void* buf, size_t len, VipsImage** out, double dpi, double scale, gboolean unlimited, const char* stylesheet, gboolean high_bitdepth, gboolean memory, VipsAccess access, VipsFailOn fail_on, gboolean revalidate);

int purevipsgen_svgload_source(VipsSourceCustom* source, VipsImage** out);
int purevipsgen_svgload_source_with_options(VipsSourceCustom* source, VipsImage** out, double dpi, double scale, gboolean unlimited, const char* stylesheet, gboolean high_bitdepth, gboolean memory, VipsAccess access, VipsFailOn fail_on, gboolean revalidate);

int purevipsgen_switch(VipsImage** tests, VipsImage** out, int n);

int purevipsgen_system(const char* cmd_format);
int purevipsgen_system_with_options(const char* cmd_format, VipsImage** in, int in_n, const char* out_format, const char* in_format);

int purevipsgen_text(VipsImage** out, const char* text);
int purevipsgen_text_with_options(VipsImage** out, const char* text, const char* font, gint width, gint height, VipsAlign align, gboolean justify, gint dpi, gint spacing, const char* fontfile, gboolean rgba, VipsTextWrap wrap, gint* autofit_dpi);

int purevipsgen_thumbnail(const char* filename, VipsImage** out, gint width);
int purevipsgen_thumbnail_with_options(const char* filename, VipsImage** out, gint width, gint height, VipsSize size, gboolean no_rotate, VipsInteresting crop, gboolean linear, const char* input_profile, const char* output_profile, VipsIntent intent, VipsFailOn fail_on);

int purevipsgen_thumbnail_buffer(void* buf, size_t len, VipsImage** out, gint width);
int purevipsgen_thumbnail_buffer_with_options(void* buf, size_t len, VipsImage** out, gint width, const char* option_string, gint height, VipsSize size, gboolean no_rotate, VipsInteresting crop, gboolean linear, const char* input_profile, const char* output_profile, VipsIntent intent, VipsFailOn fail_on);

int purevipsgen_thumbnail_image(VipsImage* in, VipsImage** out, gint width);
int purevipsgen_thumbnail_image_with_options(VipsImage* in, VipsImage** out, gint width, gint height, VipsSize size, gboolean no_rotate, VipsInteresting crop, gboolean linear, const char* input_profile, const char* output_profile, VipsIntent intent, VipsFailOn fail_on);

int purevipsgen_thumbnail_source(VipsSourceCustom* source, VipsImage** out, gint width);
int purevipsgen_thumbnail_source_with_options(VipsSourceCustom* source, VipsImage** out, gint width, const char* option_string, gint height, VipsSize size, gboolean no_rotate, VipsInteresting crop, gboolean linear, const char* input_profile, const char* output_profile, VipsIntent intent, VipsFailOn fail_on);

int purevipsgen_tiffload(const char* filename, VipsImage** out);
int purevipsgen_tiffload_with_options(const char* filename, VipsImage** out, gint page, gint n, gboolean autorotate, gint subifd, gboolean unlimited, gboolean memory, VipsAccess access, VipsFailOn fail_on, gboolean revalidate);

int purevipsgen_tiffload_buffer(void* buf, size_t len, VipsImage** out);
int purevipsgen_tiffload_buffer_with_options(void* buf, size_t len, VipsImage** out, gint page, gint n, gboolean autorotate, gint subifd, gboolean unlimited, gboolean memory, VipsAccess access, VipsFailOn fail_on, gboolean revalidate);

int purevipsgen_tiffload_source(VipsSourceCustom* source, VipsImage** out);
int purevipsgen_tiffload_source_with_options(VipsSourceCustom* source, VipsImage** out, gint page, gint n, gboolean autorotate, gint subifd, gboolean unlimited, gboolean memory, VipsAccess access, VipsFailOn fail_on, gboolean revalidate);

int purevipsgen_tiffsave(VipsImage* in, const char* filename);
int purevipsgen_tiffsave_with_options(VipsImage* in, const char* filename, VipsForeignTiffCompression compression, gint Q, VipsForeignTiffPredictor predictor, gboolean tile, gint tile_width, gint tile_height, gboolean pyramid, gboolean miniswhite, gint bitdepth, VipsForeignTiffResunit resunit, double xres, double yres, gboolean bigtiff, gboolean properties, VipsRegionShrink region_shrink, gint level, gboolean lossless, VipsForeignDzDepth depth, gboolean subifd, gboolean premultiply, VipsForeignKeep keep, double* background, int background_n, gint page_height, const char* profile);

int purevipsgen_tiffsave_buffer(VipsImage* in, void** buf, size_t* len);
int purevipsgen_tiffsave_buffer_with_options(VipsImage* in, void** buf, size_t* len, VipsForeignTiffCompression compression, gint Q, VipsForeignTiffPredictor predictor, gboolean tile, gint tile_width, gint tile_height, gboolean pyramid, gboolean miniswhite, gint bitdepth, VipsForeignTiffResunit resunit, double xres, double yres, gboolean bigtiff, gboolean properties, VipsRegionShrink region_shrink, gint level, gboolean lossless, VipsForeignDzDepth depth, gboolean subifd, gboolean premultiply, VipsForeignKeep keep, double* background, int background_n, gint page_height, const char* profile);

int purevipsgen_tiffsave_target(VipsImage* in, VipsTargetCustom* target);
int purevipsgen_tiffsave_target_with_options(VipsImage* in, VipsTargetCustom* target, VipsForeignTiffCompression compression, gint Q, VipsForeignTiffPredictor predictor, gboolean tile, gint tile_width, gint tile_height, gboolean pyramid, gboolean miniswhite, gint bitdepth, VipsForeignTiffResunit resunit, double xres, double yres, gboolean bigtiff, gboolean properties, VipsRegionShrink region_shrink, gint level, gboolean lossless, VipsForeignDzDepth depth, gboolean subifd, gboolean premultiply, VipsForeignKeep keep, double* background, int background_n, gint page_height, const char* profile);

int purevipsgen_tilecache(VipsImage* in, VipsImage** out);
int purevipsgen_tilecache_with_options(VipsImage* in, VipsImage** out, gint tile_width, gint tile_height, gint max_tiles, VipsAccess access, gboolean threaded, gboolean persistent);

int purevipsgen_tonelut(VipsImage** out);
int purevipsgen_tonelut_with_options(VipsImage** out, gint in_max, gint out_max, double Lb, double Lw, double Ps, double Pm, double Ph, double S, double M, double H);

int purevipsgen_transpose3d(VipsImage* in, VipsImage** out);
int purevipsgen_transpose3d_with_options(VipsImage* in, VipsImage** out, gint page_height);

int purevipsgen_unpremultiply(VipsImage* in, VipsImage** out);
int purevipsgen_unpremultiply_with_options(VipsImage* in, VipsImage** out, double max_alpha, gint alpha_band);

int purevipsgen_vipsload(const char* filename, VipsImage** out);
int purevipsgen_vipsload_with_options(const char* filename, VipsImage** out, gboolean memory, VipsAccess access, VipsFailOn fail_on, gboolean revalidate);

int purevipsgen_vipsload_source(VipsSourceCustom* source, VipsImage** out);
int purevipsgen_vipsload_source_with_options(VipsSourceCustom* source, VipsImage** out, gboolean memory, VipsAccess access, VipsFailOn fail_on, gboolean revalidate);

int purevipsgen_vipssave(VipsImage* in, const char* filename);
int purevipsgen_vipssave_with_options(VipsImage* in, const char* filename, VipsForeignKeep keep, double* background, int background_n, gint page_height, const char* profile);

int purevipsgen_vipssave_target(VipsImage* in, VipsTargetCustom* target);
int purevipsgen_vipssave_target_with_options(VipsImage* in, VipsTargetCustom* target, VipsForeignKeep keep, double* background, int background_n, gint page_height, const char* profile);

int purevipsgen_webpload(const char* filename, VipsImage** out);
int purevipsgen_webpload_with_options(const char* filename, VipsImage** out, gint page, gint n, double scale, gboolean memory, VipsAccess access, VipsFailOn fail_on, gboolean revalidate);

int purevipsgen_webpload_buffer(void* buf, size_t len, VipsImage** out);
int purevipsgen_webpload_buffer_with_options(void* buf, size_t len, VipsImage** out, gint page, gint n, double scale, gboolean memory, VipsAccess access, VipsFailOn fail_on, gboolean revalidate);

int purevipsgen_webpload_source(VipsSourceCustom* source, VipsImage** out);
int purevipsgen_webpload_source_with_options(VipsSourceCustom* source, VipsImage** out, gint page, gint n, double scale, gboolean memory, VipsAccess access, VipsFailOn fail_on, gboolean revalidate);

int purevipsgen_webpsave(VipsImage* in, const char* filename);
int purevipsgen_webpsave_with_options(VipsImage* in, const char* filename, gint Q, gboolean lossless, VipsForeignWebpPreset preset, gboolean smart_subsample, gboolean near_lossless, gint alpha_q, gboolean min_size, gint kmin, gint kmax, gint effort, gint target_size, gboolean mixed, gboolean smart_deblock, gint passes, VipsForeignKeep keep, double* background, int background_n, gint page_height, const char* profile);

int purevipsgen_webpsave_buffer(VipsImage* in, void** buf, size_t* len);
int purevipsgen_webpsave_buffer_with_options(VipsImage* in, void** buf, size_t* len, gint Q, gboolean lossless, VipsForeignWebpPreset preset, gboolean smart_subsample, gboolean near_lossless, gint alpha_q, gboolean min_size, gint kmin, gint kmax, gint effort, gint target_size, gboolean mixed, gboolean smart_deblock, gint passes, VipsForeignKeep keep, double* background, int background_n, gint page_height, const char* profile);

int purevipsgen_webpsave_target(VipsImage* in, VipsTargetCustom* target);
int purevipsgen_webpsave_target_with_options(VipsImage* in, VipsTargetCustom* target, gint Q, gboolean lossless, VipsForeignWebpPreset preset, gboolean smart_subsample, gboolean near_lossless, gint alpha_q, gboolean min_size, gint kmin, gint kmax, gint effort, gint target_size, gboolean mixed, gboolean smart_deblock, gint passes, VipsForeignKeep keep, double* background, int background_n, gint page_height, const char* profile);

int purevipsgen_worley(VipsImage** out, gint width, gint height);
int purevipsgen_worley_with_options(VipsImage** out, gint width, gint height, gint cell_size, gint seed);

int purevipsgen_wrap(VipsImage* in, VipsImage** out);
int purevipsgen_wrap_with_options(VipsImage* in, VipsImage** out, gint x, gint y);

int purevipsgen_xyz(VipsImage** out, gint width, gint height);
int purevipsgen_xyz_with_options(VipsImage** out, gint width, gint height, gint csize, gint dsize, gint esize);

int purevipsgen_zone(VipsImage** out, gint width, gint height);
int purevipsgen_zone_with_options(VipsImage** out, gint width, gint height, gboolean uchar);

int purevipsgen_zoom(VipsImage* input, VipsImage** out, gint xfac, gint yfac);


// Custom operations

int purevipsgen_image_new_from_source(VipsSourceCustom *source, VipsImage **out);
int purevipsgen_image_new_from_source_with_option(VipsSourceCustom *source, VipsImage **out, const char *option_string);
int purevipsgen_image_new_from_file(const char *name, VipsImage **out);
int purevipsgen_image_new_from_file_with_option(const char *name, VipsImage **out, const char *option_string);
int purevipsgen_image_new_from_buffer(const void *buf, size_t len, VipsImage **out);
int purevipsgen_image_new_from_buffer_with_option(const void *buf, size_t len, VipsImage **out, const char *option_string);
int purevipsgen_image_new_from_memory(const void *buf, size_t len, int width, int height, int bands, VipsImage **out);
void purevipsgen_clear_image(VipsImage **image);

int purevipsgen_remove_exif(VipsImage *in, VipsImage **out);
int purevipsgen_embed_multi_page(VipsImage *in, VipsImage **out, int left, int top, int width, int height, int extend);
int purevipsgen_embed_multi_page_background(VipsImage *in, VipsImage **out, int left, int top, int width, int height, double r, double g, double b, double a);
int purevipsgen_extract_area_multi_page(VipsImage *in, VipsImage **out, int left, int top, int width, int height);
int purevipsgen_rot_multi_page(VipsImage *in, VipsImage **out, VipsAngle angle);
int purevipsgen_image_write_to_memory(VipsImage *in, void **buf, size_t *len);
