// Code generated by github.com/upamune/purevipsgen from libvips 8.17.0; DO NOT EDIT.

#include <stdlib.h>
#include <vips/vips.h>

extern long long goSourceRead(void*, void *, long long);
extern long long goSourceSeek(void*, long long, int);
extern long long goTargetWrite(void*, void *, long long);
extern long long goTargetSeek(void*, long long, int);

static gint64 go_read(VipsSourceCustom *source_custom, void *buffer, gint64 length, void* ptr);
static gint64 go_source_seek(VipsSourceCustom *source_custom, gint64 offset, int whence, void* ptr);
static gint64 go_write(VipsTargetCustom *target_custom, void *buffer, gint64 length, void* ptr);
static gint64 go_target_seek(VipsTargetCustom *target_custom, gint64 offset, int whence, void* ptr);

VipsSourceCustom * create_go_custom_source(void* ptr);
VipsSourceCustom * create_go_custom_source_with_seek(void* ptr);
VipsTargetCustom * create_go_custom_target(void* ptr);
VipsTargetCustom * create_go_custom_target_with_seek(void* ptr);

void clear_source(VipsSourceCustom **source_custom);
void clear_target(VipsTargetCustom **target_custom);
