// Code generated by github.com/upamune/purevipsgen from libvips 8.17.0; DO NOT EDIT.

package vips

import (
	"strings"
)

// ImageType represents an image type
type ImageType string

// ImageType enum
const (
	ImageTypeUnknown ImageType = "unknown"
	ImageTypeJpeg ImageType = "jpeg"
	ImageTypeGif ImageType = "gif"
	ImageTypePng ImageType = "png"
	ImageTypeWebp ImageType = "webp"
	ImageTypeHeif ImageType = "heif"
	ImageTypeSvg ImageType = "svg"
	ImageTypeTiff ImageType = "tiff"
	ImageTypeJp2k ImageType = "jp2k"
	ImageTypeAvif ImageType = "avif"
	ImageTypePdf ImageType = "pdf"
	ImageTypeBmp ImageType = "bmp"
	ImageTypeMagick ImageType = "magick"
	ImageTypeAnalyze ImageType = "analyze"
	ImageTypeCsv ImageType = "csv"
	ImageTypeDz ImageType = "dz"
	ImageTypeFits ImageType = "fits"
	ImageTypeJxl ImageType = "jxl"
	ImageTypeMat ImageType = "mat"
	ImageTypeMatrix ImageType = "matrix"
	ImageTypeOpenexr ImageType = "openexr"
	ImageTypeOpenslide ImageType = "openslide"
	ImageTypePpm ImageType = "ppm"
	ImageTypeRad ImageType = "rad"
	ImageTypeRaw ImageType = "raw"
	ImageTypeVips ImageType = "vips"
)


// Access represents VipsAccess type
type Access int

// Access enum
const (
	AccessRandom Access = 0
	AccessSequential Access = 1
	AccessSequentialUnbuffered Access = 2
	AccessLast Access = 3
)

// Align represents VipsAlign type
type Align int

// Align enum
const (
	AlignLow Align = 0
	AlignCentre Align = 1
	AlignHigh Align = 2
	AlignLast Align = 3
)

// Angle represents VipsAngle type
type Angle int

// Angle enum
const (
	AngleD0 Angle = 0
	AngleD90 Angle = 1
	AngleD180 Angle = 2
	AngleD270 Angle = 3
	AngleLast Angle = 4
)

// Angle45 represents VipsAngle45 type
type Angle45 int

// Angle45 enum
const (
	Angle45D0 Angle45 = 0
	Angle45D45 Angle45 = 1
	Angle45D90 Angle45 = 2
	Angle45D135 Angle45 = 3
	Angle45D180 Angle45 = 4
	Angle45D225 Angle45 = 5
	Angle45D270 Angle45 = 6
	Angle45D315 Angle45 = 7
	Angle45Last Angle45 = 8
)

// BandFormat represents VipsBandFormat type
type BandFormat int

// BandFormat enum
const (
	BandFormatNotset BandFormat = -1
	BandFormatUchar BandFormat = 0
	BandFormatChar BandFormat = 1
	BandFormatUshort BandFormat = 2
	BandFormatShort BandFormat = 3
	BandFormatUint BandFormat = 4
	BandFormatInt BandFormat = 5
	BandFormatFloat BandFormat = 6
	BandFormatComplex BandFormat = 7
	BandFormatDouble BandFormat = 8
	BandFormatDpcomplex BandFormat = 9
	BandFormatLast BandFormat = 10
)

// BlendMode represents VipsBlendMode type
type BlendMode int

// BlendMode enum
const (
	BlendModeClear BlendMode = 0
	BlendModeSource BlendMode = 1
	BlendModeOver BlendMode = 2
	BlendModeIn BlendMode = 3
	BlendModeOut BlendMode = 4
	BlendModeAtop BlendMode = 5
	BlendModeDest BlendMode = 6
	BlendModeDestOver BlendMode = 7
	BlendModeDestIn BlendMode = 8
	BlendModeDestOut BlendMode = 9
	BlendModeDestAtop BlendMode = 10
	BlendModeXor BlendMode = 11
	BlendModeAdd BlendMode = 12
	BlendModeSaturate BlendMode = 13
	BlendModeMultiply BlendMode = 14
	BlendModeScreen BlendMode = 15
	BlendModeOverlay BlendMode = 16
	BlendModeDarken BlendMode = 17
	BlendModeLighten BlendMode = 18
	BlendModeColourDodge BlendMode = 19
	BlendModeColourBurn BlendMode = 20
	BlendModeHardLight BlendMode = 21
	BlendModeSoftLight BlendMode = 22
	BlendModeDifference BlendMode = 23
	BlendModeExclusion BlendMode = 24
	BlendModeLast BlendMode = 25
)

// Coding represents VipsCoding type
type Coding int

// Coding enum
const (
	CodingError Coding = -1
	CodingNone Coding = 0
	CodingLabq Coding = 2
	CodingRad Coding = 6
	CodingLast Coding = 7
)

// Combine represents VipsCombine type
type Combine int

// Combine enum
const (
	CombineMax Combine = 0
	CombineSum Combine = 1
	CombineMin Combine = 2
	CombineLast Combine = 3
)

// CombineMode represents VipsCombineMode type
type CombineMode int

// CombineMode enum
const (
	CombineModeSet CombineMode = 0
	CombineModeAdd CombineMode = 1
	CombineModeLast CombineMode = 2
)

// CompassDirection represents VipsCompassDirection type
type CompassDirection int

// CompassDirection enum
const (
	CompassDirectionCentre CompassDirection = 0
	CompassDirectionNorth CompassDirection = 1
	CompassDirectionEast CompassDirection = 2
	CompassDirectionSouth CompassDirection = 3
	CompassDirectionWest CompassDirection = 4
	CompassDirectionNorthEast CompassDirection = 5
	CompassDirectionSouthEast CompassDirection = 6
	CompassDirectionSouthWest CompassDirection = 7
	CompassDirectionNorthWest CompassDirection = 8
	CompassDirectionLast CompassDirection = 9
)

// Direction represents VipsDirection type
type Direction int

// Direction enum
const (
	DirectionHorizontal Direction = 0
	DirectionVertical Direction = 1
	DirectionLast Direction = 2
)

// Extend represents VipsExtend type
type Extend int

// Extend enum
const (
	ExtendBlack Extend = 0
	ExtendCopy Extend = 1
	ExtendRepeat Extend = 2
	ExtendMirror Extend = 3
	ExtendWhite Extend = 4
	ExtendBackground Extend = 5
	ExtendLast Extend = 6
)

// FailOn represents VipsFailOn type
type FailOn int

// FailOn enum
const (
	FailOnNone FailOn = 0
	FailOnTruncated FailOn = 1
	FailOnError FailOn = 2
	FailOnWarning FailOn = 3
	FailOnLast FailOn = 4
)

// DzContainer represents VipsForeignDzContainer type
type DzContainer int

// DzContainer enum
const (
	DzContainerFs DzContainer = 0
	DzContainerZip DzContainer = 1
	DzContainerSzi DzContainer = 2
	DzContainerLast DzContainer = 3
)

// DzDepth represents VipsForeignDzDepth type
type DzDepth int

// DzDepth enum
const (
	DzDepthOnepixel DzDepth = 0
	DzDepthOnetile DzDepth = 1
	DzDepthOne DzDepth = 2
	DzDepthLast DzDepth = 3
)

// DzLayout represents VipsForeignDzLayout type
type DzLayout int

// DzLayout enum
const (
	DzLayoutDz DzLayout = 0
	DzLayoutZoomify DzLayout = 1
	DzLayoutGoogle DzLayout = 2
	DzLayoutIiif DzLayout = 3
	DzLayoutIiif3 DzLayout = 4
	DzLayoutLast DzLayout = 5
)

// Flags represents VipsForeignFlags type
type Flags int

// Flags enum
const (
	FlagsNone Flags = 0
	FlagsPartial Flags = 1
	FlagsBigendian Flags = 2
	FlagsSequential Flags = 4
	FlagsAll Flags = 7
)

// HeifCompression represents VipsForeignHeifCompression type
type HeifCompression int

// HeifCompression enum
const (
	HeifCompressionHevc HeifCompression = 1
	HeifCompressionAvc HeifCompression = 2
	HeifCompressionJpeg HeifCompression = 3
	HeifCompressionAv1 HeifCompression = 4
	HeifCompressionLast HeifCompression = 5
)

// HeifEncoder represents VipsForeignHeifEncoder type
type HeifEncoder int

// HeifEncoder enum
const (
	HeifEncoderAuto HeifEncoder = 0
	HeifEncoderAom HeifEncoder = 1
	HeifEncoderRav1e HeifEncoder = 2
	HeifEncoderSvt HeifEncoder = 3
	HeifEncoderX265 HeifEncoder = 4
	HeifEncoderLast HeifEncoder = 5
)

// Keep represents VipsForeignKeep type
type Keep int

// Keep enum
const (
	KeepNone Keep = -1
	KeepExif Keep = 1
	KeepXmp Keep = 2
	KeepIptc Keep = 4
	KeepIcc Keep = 8
	KeepOther Keep = 16
	KeepAll Keep = 31
)

// PngFilter represents VipsForeignPngFilter type
type PngFilter int

// PngFilter enum
const (
	PngFilterNone PngFilter = 8
	PngFilterSub PngFilter = 16
	PngFilterUp PngFilter = 32
	PngFilterAvg PngFilter = 64
	PngFilterPaeth PngFilter = 128
	PngFilterAll PngFilter = 248
)

// PpmFormat represents VipsForeignPpmFormat type
type PpmFormat int

// PpmFormat enum
const (
	PpmFormatPbm PpmFormat = 0
	PpmFormatPgm PpmFormat = 1
	PpmFormatPpm PpmFormat = 2
	PpmFormatPfm PpmFormat = 3
	PpmFormatPnm PpmFormat = 4
	PpmFormatLast PpmFormat = 5
)

// Subsample represents VipsForeignSubsample type
type Subsample int

// Subsample enum
const (
	SubsampleAuto Subsample = 0
	SubsampleOn Subsample = 1
	SubsampleOff Subsample = 2
	SubsampleLast Subsample = 3
)

// TiffCompression represents VipsForeignTiffCompression type
type TiffCompression int

// TiffCompression enum
const (
	TiffCompressionNone TiffCompression = 0
	TiffCompressionJpeg TiffCompression = 1
	TiffCompressionDeflate TiffCompression = 2
	TiffCompressionPackbits TiffCompression = 3
	TiffCompressionCcittfax4 TiffCompression = 4
	TiffCompressionLzw TiffCompression = 5
	TiffCompressionWebp TiffCompression = 6
	TiffCompressionZstd TiffCompression = 7
	TiffCompressionJp2k TiffCompression = 8
	TiffCompressionLast TiffCompression = 9
)

// TiffPredictor represents VipsForeignTiffPredictor type
type TiffPredictor int

// TiffPredictor enum
const (
	TiffPredictorNone TiffPredictor = 1
	TiffPredictorHorizontal TiffPredictor = 2
	TiffPredictorFloat TiffPredictor = 3
	TiffPredictorLast TiffPredictor = 4
)

// TiffResunit represents VipsForeignTiffResunit type
type TiffResunit int

// TiffResunit enum
const (
	TiffResunitCm TiffResunit = 0
	TiffResunitInch TiffResunit = 1
	TiffResunitLast TiffResunit = 2
)

// WebpPreset represents VipsForeignWebpPreset type
type WebpPreset int

// WebpPreset enum
const (
	WebpPresetDefault WebpPreset = 0
	WebpPresetPicture WebpPreset = 1
	WebpPresetPhoto WebpPreset = 2
	WebpPresetDrawing WebpPreset = 3
	WebpPresetIcon WebpPreset = 4
	WebpPresetText WebpPreset = 5
	WebpPresetLast WebpPreset = 6
)

// Intent represents VipsIntent type
type Intent int

// Intent enum
const (
	IntentPerceptual Intent = 0
	IntentRelative Intent = 1
	IntentSaturation Intent = 2
	IntentAbsolute Intent = 3
	IntentAuto Intent = 32
	IntentLast Intent = 33
)

// Interesting represents VipsInteresting type
type Interesting int

// Interesting enum
const (
	InterestingNone Interesting = 0
	InterestingCentre Interesting = 1
	InterestingEntropy Interesting = 2
	InterestingAttention Interesting = 3
	InterestingLow Interesting = 4
	InterestingHigh Interesting = 5
	InterestingAll Interesting = 6
	InterestingLast Interesting = 7
)

// Interpretation represents VipsInterpretation type
type Interpretation int

// Interpretation enum
const (
	InterpretationError Interpretation = -1
	InterpretationMultiband Interpretation = 0
	InterpretationBW Interpretation = 1
	InterpretationHistogram Interpretation = 10
	InterpretationXyz Interpretation = 12
	InterpretationLab Interpretation = 13
	InterpretationCmyk Interpretation = 15
	InterpretationLabq Interpretation = 16
	InterpretationRgb Interpretation = 17
	InterpretationCmc Interpretation = 18
	InterpretationLch Interpretation = 19
	InterpretationLabs Interpretation = 21
	InterpretationSrgb Interpretation = 22
	InterpretationYxy Interpretation = 23
	InterpretationFourier Interpretation = 24
	InterpretationRgb16 Interpretation = 25
	InterpretationGrey16 Interpretation = 26
	InterpretationMatrix Interpretation = 27
	InterpretationScrgb Interpretation = 28
	InterpretationHsv Interpretation = 29
	InterpretationLast Interpretation = 30
)

// Kernel represents VipsKernel type
type Kernel int

// Kernel enum
const (
	KernelNearest Kernel = 0
	KernelLinear Kernel = 1
	KernelCubic Kernel = 2
	KernelMitchell Kernel = 3
	KernelLanczos2 Kernel = 4
	KernelLanczos3 Kernel = 5
	KernelMks2013 Kernel = 6
	KernelMks2021 Kernel = 7
	KernelLast Kernel = 8
)

// OperationBoolean represents VipsOperationBoolean type
type OperationBoolean int

// OperationBoolean enum
const (
	OperationBooleanAnd OperationBoolean = 0
	OperationBooleanOr OperationBoolean = 1
	OperationBooleanEor OperationBoolean = 2
	OperationBooleanLshift OperationBoolean = 3
	OperationBooleanRshift OperationBoolean = 4
	OperationBooleanLast OperationBoolean = 5
)

// OperationComplex represents VipsOperationComplex type
type OperationComplex int

// OperationComplex enum
const (
	OperationComplexPolar OperationComplex = 0
	OperationComplexRect OperationComplex = 1
	OperationComplexConj OperationComplex = 2
	OperationComplexLast OperationComplex = 3
)

// OperationComplex2 represents VipsOperationComplex2 type
type OperationComplex2 int

// OperationComplex2 enum
const (
	OperationComplex2CrossPhase OperationComplex2 = 0
	OperationComplex2Last OperationComplex2 = 1
)

// OperationComplexget represents VipsOperationComplexget type
type OperationComplexget int

// OperationComplexget enum
const (
	OperationComplexgetReal OperationComplexget = 0
	OperationComplexgetImag OperationComplexget = 1
	OperationComplexgetLast OperationComplexget = 2
)

// OperationMath represents VipsOperationMath type
type OperationMath int

// OperationMath enum
const (
	OperationMathSin OperationMath = 0
	OperationMathCos OperationMath = 1
	OperationMathTan OperationMath = 2
	OperationMathAsin OperationMath = 3
	OperationMathAcos OperationMath = 4
	OperationMathAtan OperationMath = 5
	OperationMathLog OperationMath = 6
	OperationMathLog10 OperationMath = 7
	OperationMathExp OperationMath = 8
	OperationMathExp10 OperationMath = 9
	OperationMathSinh OperationMath = 10
	OperationMathCosh OperationMath = 11
	OperationMathTanh OperationMath = 12
	OperationMathAsinh OperationMath = 13
	OperationMathAcosh OperationMath = 14
	OperationMathAtanh OperationMath = 15
	OperationMathLast OperationMath = 16
)

// OperationMath2 represents VipsOperationMath2 type
type OperationMath2 int

// OperationMath2 enum
const (
	OperationMath2Pow OperationMath2 = 0
	OperationMath2Wop OperationMath2 = 1
	OperationMath2Atan2 OperationMath2 = 2
	OperationMath2Last OperationMath2 = 3
)

// OperationMorphology represents VipsOperationMorphology type
type OperationMorphology int

// OperationMorphology enum
const (
	OperationMorphologyErode OperationMorphology = 0
	OperationMorphologyDilate OperationMorphology = 1
	OperationMorphologyLast OperationMorphology = 2
)

// OperationRelational represents VipsOperationRelational type
type OperationRelational int

// OperationRelational enum
const (
	OperationRelationalEqual OperationRelational = 0
	OperationRelationalNoteq OperationRelational = 1
	OperationRelationalLess OperationRelational = 2
	OperationRelationalLesseq OperationRelational = 3
	OperationRelationalMore OperationRelational = 4
	OperationRelationalMoreeq OperationRelational = 5
	OperationRelationalLast OperationRelational = 6
)

// OperationRound represents VipsOperationRound type
type OperationRound int

// OperationRound enum
const (
	OperationRoundRint OperationRound = 0
	OperationRoundCeil OperationRound = 1
	OperationRoundFloor OperationRound = 2
	OperationRoundLast OperationRound = 3
)

// PCS represents VipsPCS type
type PCS int

// PCS enum
const (
	PcsLab PCS = 0
	PcsXyz PCS = 1
	PcsLast PCS = 2
)

// Precision represents VipsPrecision type
type Precision int

// Precision enum
const (
	PrecisionInteger Precision = 0
	PrecisionFloat Precision = 1
	PrecisionApproximate Precision = 2
	PrecisionLast Precision = 3
)

// RegionShrink represents VipsRegionShrink type
type RegionShrink int

// RegionShrink enum
const (
	RegionShrinkMean RegionShrink = 0
	RegionShrinkMedian RegionShrink = 1
	RegionShrinkMode RegionShrink = 2
	RegionShrinkMax RegionShrink = 3
	RegionShrinkMin RegionShrink = 4
	RegionShrinkNearest RegionShrink = 5
	RegionShrinkLast RegionShrink = 6
)

// SdfShape represents VipsSdfShape type
type SdfShape int

// SdfShape enum
const (
	SdfShapeCircle SdfShape = 0
	SdfShapeBox SdfShape = 1
	SdfShapeRoundedBox SdfShape = 2
	SdfShapeLine SdfShape = 3
	SdfShapeLast SdfShape = 4
)

// Size represents VipsSize type
type Size int

// Size enum
const (
	SizeBoth Size = 0
	SizeUp Size = 1
	SizeDown Size = 2
	SizeForce Size = 3
	SizeLast Size = 4
)

// TextWrap represents VipsTextWrap type
type TextWrap int

// TextWrap enum
const (
	TextWrapWord TextWrap = 0
	TextWrapChar TextWrap = 1
	TextWrapWordChar TextWrap = 2
	TextWrapNone TextWrap = 3
	TextWrapLast TextWrap = 4
)


// imageMimeTypes map the various image types to its mime type representation
var imageMimeTypes = map[ImageType]string{
	ImageTypeJpeg: "image/jpeg",
	ImageTypeGif: "image/gif",
	ImageTypePng: "image/png",
	ImageTypeWebp: "image/webp",
	ImageTypeHeif: "image/heif",
	ImageTypeSvg: "image/svg+xml",
	ImageTypeTiff: "image/tiff",
	ImageTypeJp2k: "image/jp2",
	ImageTypeAvif: "image/avif",
	ImageTypePdf: "application/pdf",
	ImageTypeBmp: "image/bmp",
	ImageTypeAnalyze: "application/x-analyze",
	ImageTypeCsv: "text/csv",
	ImageTypeDz: "image/x-deepzoom",
	ImageTypeFits: "image/fits",
	ImageTypeJxl: "image/jxl",
	ImageTypeMat: "application/x-matlab-data",
	ImageTypeMatrix: "application/x-matrix",
	ImageTypeOpenexr: "image/openexr",
	ImageTypeOpenslide: "application/x-openslide",
	ImageTypePpm: "image/x-portable-pixmap",
	ImageTypeRad: "image/rad",
	ImageTypeRaw: "image/raw",
	ImageTypeVips: "image/vnd.libvips",
}

// MimeType returns the MIME type for the image type.
func (imageType ImageType) MimeType() (mime string, ok bool) {
	mime, ok = imageMimeTypes[imageType]
	return
}

// vipsDetermineImageType determine the image type from loader metadata
func vipsDetermineImageType(in vipsImageRef) ImageType {
	if in != nil {
		if vipsLoader, ok := vipsImageGetMetaLoader(in); ok {
			if strings.HasPrefix(vipsLoader, "jpeg") {
				return ImageTypeJpeg
			}
			if strings.HasPrefix(vipsLoader, "gif") {
				return ImageTypeGif
			}
			if strings.HasPrefix(vipsLoader, "png") {
				return ImageTypePng
			}
			if strings.HasPrefix(vipsLoader, "webp") {
				return ImageTypeWebp
			}
			if strings.HasPrefix(vipsLoader, "heif") {
				return ImageTypeHeif
			}
			if strings.HasPrefix(vipsLoader, "svg") {
				return ImageTypeSvg
			}
			if strings.HasPrefix(vipsLoader, "tiff") {
				return ImageTypeTiff
			}
			if strings.HasPrefix(vipsLoader, "jp2k") {
				return ImageTypeJp2k
			}
			if strings.HasPrefix(vipsLoader, "pdf") {
				return ImageTypePdf
			}
			if strings.HasPrefix(vipsLoader, "analyze") {
				return ImageTypeAnalyze
			}
			if strings.HasPrefix(vipsLoader, "csv") {
				return ImageTypeCsv
			}
			if strings.HasPrefix(vipsLoader, "fits") {
				return ImageTypeFits
			}
			if strings.HasPrefix(vipsLoader, "jxl") {
				return ImageTypeJxl
			}
			if strings.HasPrefix(vipsLoader, "mat") {
				return ImageTypeMat
			}
			if strings.HasPrefix(vipsLoader, "matrix") {
				return ImageTypeMatrix
			}
			if strings.HasPrefix(vipsLoader, "openexr") {
				return ImageTypeOpenexr
			}
			if strings.HasPrefix(vipsLoader, "openslide") {
				return ImageTypeOpenslide
			}
			if strings.HasPrefix(vipsLoader, "ppm") {
				return ImageTypePpm
			}
			if strings.HasPrefix(vipsLoader, "rad") {
				return ImageTypeRad
			}
			if strings.HasPrefix(vipsLoader, "raw") {
				return ImageTypeRaw
			}
			if strings.HasPrefix(vipsLoader, "vips") {
				return ImageTypeVips
			}
			if strings.HasPrefix(vipsLoader, "magick") {
				return ImageTypeMagick
			}
			
		}
	}
	return ImageTypeUnknown
}

// Interpolate represents VipsInterpolate type
type Interpolate struct {
	interp vipsInterpolateRef
}

// InterpolateType represents the type of interpolation to use
type InterpolateType string

// InterpolateType enum - these values match the predefined interpolators in libvips
const (
	InterpolateNearest  InterpolateType = "nearest"
	InterpolateBilinear InterpolateType = "bilinear"
	InterpolateBicubic  InterpolateType = "bicubic"
	InterpolateLbb      InterpolateType = "lbb"      // Lanczos3
	InterpolateNohalo   InterpolateType = "nohalo"
	InterpolateVsqbs    InterpolateType = "vsqbs"
)

// NewInterpolate creates a new Interpolate with the given name
// Valid names include: "nearest", "bilinear", "bicubic", "lbb", "nohalo", "vsqbs"
func NewInterpolate(name InterpolateType) *Interpolate {
	Startup(nil)
	var f func(string) vipsInterpolateRef
	registerVipsFunc(&f, "vips_interpolate_new")
	interp := f(cString(string(name)))
	if interp == nil {
		// Default to bilinear if requested interpolator not found
		clearVipsError()
		interp = f(cString("bilinear"))
	}
	return &Interpolate{interp: interp}
}

// Close frees the interpolator resources
func (i *Interpolate) Close() {
	if i != nil && i.interp != nil {
		gObjectUnref(i.interp)
		i.interp = nil
	}
}
